-- Create favorites table
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id text not null,
  question text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, question)
);

-- Enable RLS
alter table favorites enable row level security;

-- Policies for public/anon access (since we use custom user_id string)
-- Allow anyone to select their own favorites (by user_id match)
create policy "Enable select for users based on user_id"
on favorites for select
using ( true ); -- We rely on client filtering, or we can enforce user_id check if we trust the client to send it

-- Actually, better to allow all operations for anon if we don't have auth
-- But let's try to be slightly specific
create policy "Enable all access for anon users"
on favorites for all
using ( true )
with check ( true );
